name: ci

on: push

jobs:
  build:
    strategy:
      matrix:
        container: [ ubuntu-latest, macos-latest, windows-latest ]
        build_type: [ Debug, Release ]


    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      # Fetch the dependencies. Different for each platform.
      - name: Install dependencies - Linux
        if: runner.os == 'Linux' && matrix.build_tool == 'scons'
        run: |
          sudo apt-get update
          sudo apt-get install scons

      - name: Configure
        # Configure CMake in a 'build' subdirectory.
        run: |
          ls
          mkdir -p build
          cd build
          cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..

      - name: Build
        run: |
          cmake --build build

      - name: Test
        working-directory: ${{ github.workspace }}/build
        # Execute all tests.
        run: test/cctest/cctest
