name: scons

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons

      - name: Build
        run: |
          make

      - name: Test
        run: |
          make test
