name: scons

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons

      - name: Build
        run: |
          make

      - name: Test
        run: |
          make test
