name: scons

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons

      - name: Build
        run: |
          make

      - name: Test
        run: |
          make test
